/*
 * This file is generated by jOOQ.
 */
package jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import jooq.tables.Teacher;
import jooq.tables.TeacherDetails;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class School extends SchemaImpl {

    private static final long serialVersionUID = -590656808;

    /**
     * The reference instance of <code>school</code>
     */
    public static final School SCHOOL = new School();

    /**
     * The table <code>school.teacher</code>.
     */
    public final Teacher TEACHER = jooq.tables.Teacher.TEACHER;

    /**
     * The table <code>school.teacher_details</code>.
     */
    public final TeacherDetails TEACHER_DETAILS = jooq.tables.TeacherDetails.TEACHER_DETAILS;

    /**
     * No further instances allowed
     */
    private School() {
        super("school", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Teacher.TEACHER,
            TeacherDetails.TEACHER_DETAILS);
    }
}
