/*
 * This file is generated by jOOQ.
 */
package jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import jooq.tables.Teacher;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Student extends SchemaImpl {

    private static final long serialVersionUID = 1082720763;

    /**
     * The reference instance of <code>Student</code>
     */
    public static final Student STUDENT = new Student();

    /**
     * The table <code>Student.teacher</code>.
     */
    public final Teacher TEACHER = jooq.tables.Teacher.TEACHER;

    /**
     * No further instances allowed
     */
    private Student() {
        super("Student", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Teacher.TEACHER);
    }
}
