/*
 * This file is generated by jOOQ.
 */
package jooq;


import javax.annotation.processing.Generated;

import jooq.tables.Teacher;


/**
 * Convenience access to all tables in Student
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>Student.teacher</code>.
     */
    public static final Teacher TEACHER = Teacher.TEACHER;
}
