/*
 * This file is generated by jOOQ.
 */
package jooq;


import javax.annotation.processing.Generated;

import jooq.tables.Teacher;
import jooq.tables.TeacherDetails;


/**
 * Convenience access to all tables in school
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>school.teacher</code>.
     */
    public static final Teacher TEACHER = Teacher.TEACHER;

    /**
     * The table <code>school.teacher_details</code>.
     */
    public static final TeacherDetails TEACHER_DETAILS = TeacherDetails.TEACHER_DETAILS;
}
