/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Teacher implements Serializable {

    private static final long serialVersionUID = -614831763;

    private String  name;
    private Integer age;

    public Teacher() {}

    public Teacher(Teacher value) {
        this.name = value.name;
        this.age = value.age;
    }

    public Teacher(
        String  name,
        Integer age
    ) {
        this.name = name;
        this.age = age;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getAge() {
        return this.age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Teacher (");

        sb.append(name);
        sb.append(", ").append(age);

        sb.append(")");
        return sb.toString();
    }
}
