/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeacherDetails implements Serializable {

    private static final long serialVersionUID = 17945244;

    private Integer teacherId;
    private String  address;
    private Integer salary;

    public TeacherDetails() {}

    public TeacherDetails(TeacherDetails value) {
        this.teacherId = value.teacherId;
        this.address = value.address;
        this.salary = value.salary;
    }

    public TeacherDetails(
        Integer teacherId,
        String  address,
        Integer salary
    ) {
        this.teacherId = teacherId;
        this.address = address;
        this.salary = salary;
    }

    public Integer getTeacherId() {
        return this.teacherId;
    }

    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Integer getSalary() {
        return this.salary;
    }

    public void setSalary(Integer salary) {
        this.salary = salary;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TeacherDetails (");

        sb.append(teacherId);
        sb.append(", ").append(address);
        sb.append(", ").append(salary);

        sb.append(")");
        return sb.toString();
    }
}
