/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import javax.annotation.processing.Generated;

import jooq.tables.Teacher;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeacherRecord extends TableRecordImpl<TeacherRecord> implements Record2<String, Integer> {

    private static final long serialVersionUID = -114351072;

    /**
     * Setter for <code>Student.teacher.name</code>.
     */
    public void setName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>Student.teacher.name</code>.
     */
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>Student.teacher.age</code>.
     */
    public void setAge(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>Student.teacher.age</code>.
     */
    public Integer getAge() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Teacher.TEACHER.NAME;
    }

    @Override
    public Field<Integer> field2() {
        return Teacher.TEACHER.AGE;
    }

    @Override
    public String component1() {
        return getName();
    }

    @Override
    public Integer component2() {
        return getAge();
    }

    @Override
    public String value1() {
        return getName();
    }

    @Override
    public Integer value2() {
        return getAge();
    }

    @Override
    public TeacherRecord value1(String value) {
        setName(value);
        return this;
    }

    @Override
    public TeacherRecord value2(Integer value) {
        setAge(value);
        return this;
    }

    @Override
    public TeacherRecord values(String value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TeacherRecord
     */
    public TeacherRecord() {
        super(Teacher.TEACHER);
    }

    /**
     * Create a detached, initialised TeacherRecord
     */
    public TeacherRecord(String name, Integer age) {
        super(Teacher.TEACHER);

        set(0, name);
        set(1, age);
    }
}
