/*
 * This file is generated by jOOQ.
 */
package jooq.tables.daos;


import java.util.List;

import javax.annotation.processing.Generated;

import jooq.tables.Teacher;
import jooq.tables.records.TeacherRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeacherDao extends DAOImpl<TeacherRecord, jooq.tables.pojos.Teacher, Integer> {

    /**
     * Create a new TeacherDao without any configuration
     */
    public TeacherDao() {
        super(Teacher.TEACHER, jooq.tables.pojos.Teacher.class);
    }

    /**
     * Create a new TeacherDao with an attached configuration
     */
    public TeacherDao(Configuration configuration) {
        super(Teacher.TEACHER, jooq.tables.pojos.Teacher.class, configuration);
    }

    @Override
    public Integer getId(jooq.tables.pojos.Teacher object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<jooq.tables.pojos.Teacher> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Teacher.TEACHER.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<jooq.tables.pojos.Teacher> fetchByName(String... values) {
        return fetch(Teacher.TEACHER.NAME, values);
    }

    /**
     * Fetch records that have <code>age BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<jooq.tables.pojos.Teacher> fetchRangeOfAge(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Teacher.TEACHER.AGE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>age IN (values)</code>
     */
    public List<jooq.tables.pojos.Teacher> fetchByAge(Integer... values) {
        return fetch(Teacher.TEACHER.AGE, values);
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<jooq.tables.pojos.Teacher> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Teacher.TEACHER.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<jooq.tables.pojos.Teacher> fetchById(Integer... values) {
        return fetch(Teacher.TEACHER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public jooq.tables.pojos.Teacher fetchOneById(Integer value) {
        return fetchOne(Teacher.TEACHER.ID, value);
    }
}
